name: Publish Package to npmjs

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Check out code

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        registry-url: https://registry.npmjs.org

    - name: Publish
      run: npm publish --access public
      working-directory: ui
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}