name: Publish Package to npmjs

on:
  push:
    branches: [develop]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Check out code

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 14.20.1
        registry-url: https://registry.npmjs.org
        
    - name: CI
      run: npm ci

    - name: Build
      run: npm run-script build

    - name: Publish
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}